run day part:
    cargo run -p {{day}} --bin {{part}}
create day:
    cp -r ".template/" "{{day}}"
    sed -i 's/dayXXX/{{day}}/g' {{day}}/Cargo.toml
    sed -i 's/dayXXX/{{day}}/g' {{day}}/src/bin/part1.rs
    sed -i 's/dayXXX/{{day}}/g' {{day}}/src/bin/part2.rs
    sed -i '$ d' ./Cargo.toml
    echo "    \"{{day}}\"," >> ./Cargo.toml
    echo "    ]" >> ./Cargo.toml

